export const PERMISSIONS = {
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_READ: 'USER_READ',
  ROL_CREATE: 'ROL_CREATE',
  ROL_UPDATE: 'ROL_UPDATE',
  ROL_DELETE: 'ROL_DELETE',
  ROL_READ: 'ROL_READ',
};
